[2024-06-21 23:56:35,880: INFO: main: WELCOME]
[2024-07-03 15:47:44,015: INFO: main: {'Data Ingestion Stage'}]
[2024-07-03 15:47:44,016: ERROR: main: DataIngestionTrainingPipeline.main() missing 1 required positional argument: 'self']
Traceback (most recent call last):
  File "c:\Users\heman\OneDrive\Desktop\Text Summariser\main.py", line 8, in <module>
    data_ingestion.main()
TypeError: DataIngestionTrainingPipeline.main() missing 1 required positional argument: 'self'
[2024-07-03 15:56:30,330: INFO: main: {'Data Ingestion Stage'}]
[2024-07-03 15:56:30,330: ERROR: main: DataIngestionTrainingPipeline.main() missing 1 required positional argument: 'self']
Traceback (most recent call last):
  File "c:\Users\heman\OneDrive\Desktop\Text Summariser\main.py", line 8, in <module>
    data_ingestion.main()
TypeError: DataIngestionTrainingPipeline.main() missing 1 required positional argument: 'self'
[2024-07-03 15:59:26,888: INFO: main: {'Data Ingestion Stage'}]
[2024-07-03 15:59:26,888: ERROR: main: DataIngestionTrainingPipeline.main() missing 1 required positional argument: 'self']
Traceback (most recent call last):
  File "c:\Users\heman\OneDrive\Desktop\Text Summariser\main.py", line 8, in <module>
    data_ingestion.main()
TypeError: DataIngestionTrainingPipeline.main() missing 1 required positional argument: 'self'
[2024-07-03 15:59:35,317: INFO: main: {'Data Ingestion Stage'}]
[2024-07-03 15:59:35,318: ERROR: main: name 'self' is not defined]
Traceback (most recent call last):
  File "c:\Users\heman\OneDrive\Desktop\Text Summariser\main.py", line 8, in <module>
    data_ingestion.main(self)
                        ^^^^
NameError: name 'self' is not defined
[2024-07-03 16:01:30,136: INFO: main: {'Data Ingestion Stage'}]
[2024-07-03 16:01:30,136: ERROR: main: DataIngestionTrainingPipeline.main() missing 1 required positional argument: 'self']
Traceback (most recent call last):
  File "c:\Users\heman\OneDrive\Desktop\Text Summariser\main.py", line 8, in <module>
    data_ingestion.main()
TypeError: DataIngestionTrainingPipeline.main() missing 1 required positional argument: 'self'
[2024-07-03 16:01:58,730: INFO: main: {'Data Ingestion Stage'}]
[2024-07-03 16:01:58,731: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-03 16:01:58,733: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-03 16:01:58,733: INFO: common: created directory at: artifacts]
[2024-07-03 16:01:58,734: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-03 16:02:01,597: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 3163:36F5C4:8F8CC:B9FFE:6685289E
Accept-Ranges: bytes
Date: Wed, 03 Jul 2024 10:31:59 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100025-HYD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1720002719.084788,VS0,VE720
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: f8a4b562bb808396206226b846df3ef1659b1992
Expires: Wed, 03 Jul 2024 10:36:59 GMT
Source-Age: 0

]
[2024-07-03 16:02:01,744: INFO: main: COMPLETED]
[2024-07-03 16:02:23,278: INFO: main: {'Data Ingestion Stage'}]
[2024-07-03 16:02:23,280: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-03 16:02:23,281: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-03 16:02:23,282: INFO: common: created directory at: artifacts]
[2024-07-03 16:02:23,282: INFO: common: created directory at: artifacts/data_ingestion]
[2024-07-03 16:02:26,166: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 3163:36F5C4:8F8CC:B9FFE:6685289E
Accept-Ranges: bytes
Date: Wed, 03 Jul 2024 10:32:23 GMT
Via: 1.1 varnish
X-Served-By: cache-hyd1100020-HYD
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1720002743.358593,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: e7c8e94b9d6aa55d49beabb11e04e091fe9c7772
Expires: Wed, 03 Jul 2024 10:37:23 GMT
Source-Age: 24

]
[2024-07-03 16:02:26,312: INFO: main: COMPLETED]
[2024-07-03 16:22:53,660: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-03 16:22:53,672: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-03 16:22:53,673: INFO: common: created directory at: artifacts]
[2024-07-03 16:29:49,283: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-03 16:29:49,293: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-03 16:29:49,294: INFO: common: created directory at: artifacts]
[2024-07-03 16:29:49,296: INFO: common: created directory at: artifacts/data_validation]
[2024-07-03 23:12:14,021: INFO: main: {'Data Validation Stage'}]
[2024-07-03 23:12:14,021: ERROR: main: name 'DataValidationTrainingPipeline' is not defined]
Traceback (most recent call last):
  File "c:\Users\heman\OneDrive\Desktop\Text Summariser\main.py", line 8, in <module>
    data_validation = DataValidationTrainingPipeline()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'DataValidationTrainingPipeline' is not defined. Did you mean: 'DataIngestionTrainingPipeline'?
[2024-07-03 23:12:51,867: INFO: main: {'Data Validation Stage'}]
[2024-07-03 23:12:51,867: ERROR: main: type object 'DataValiadtion' has no attribute 'main']
Traceback (most recent call last):
  File "c:\Users\heman\OneDrive\Desktop\Text Summariser\main.py", line 9, in <module>
    data_validation .main()
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'DataValiadtion' has no attribute 'main'
[2024-07-03 23:12:59,455: INFO: main: {'Data Validation Stage'}]
[2024-07-03 23:12:59,456: ERROR: main: DataValiadtion.__init__() missing 1 required positional argument: 'config']
Traceback (most recent call last):
  File "c:\Users\heman\OneDrive\Desktop\Text Summariser\main.py", line 8, in <module>
    data_validation = DataValiadtion()
                      ^^^^^^^^^^^^^^^^
TypeError: DataValiadtion.__init__() missing 1 required positional argument: 'config'
[2024-07-03 23:14:23,334: INFO: main: {'Data Validation Stage'}]
[2024-07-03 23:14:23,335: ERROR: main: name 'DataValiadtionTrainingPipeline' is not defined]
Traceback (most recent call last):
  File "c:\Users\heman\OneDrive\Desktop\Text Summariser\main.py", line 8, in <module>
    data_validation = DataValiadtionTrainingPipeline()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'DataValiadtionTrainingPipeline' is not defined. Did you mean: 'DataIngestionTrainingPipeline'?
[2024-07-03 23:15:22,528: INFO: main: {'Data Validation Stage'}]
[2024-07-03 23:15:22,529: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-03 23:15:22,531: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-03 23:15:22,531: INFO: common: created directory at: artifacts]
[2024-07-03 23:15:22,532: INFO: common: created directory at: artifacts/data_validation]
[2024-07-03 23:15:22,532: ERROR: main: name 'DataValidation' is not defined]
Traceback (most recent call last):
  File "c:\Users\heman\OneDrive\Desktop\Text Summariser\main.py", line 9, in <module>
    data_validation .main()
  File "C:\Users\heman\OneDrive\Desktop\Text Summariser\src\textsummariser\pipeline\stage2data_validation.py", line 13, in main
    data_validation = DataValidation(config=data_validation_config)
                      ^^^^^^^^^^^^^^
NameError: name 'DataValidation' is not defined. Did you mean: 'DataValiadtion'?
[2024-07-03 23:17:40,079: INFO: main: {'Data Validation Stage'}]
[2024-07-03 23:17:40,081: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-03 23:17:40,082: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-03 23:17:40,083: INFO: common: created directory at: artifacts]
[2024-07-03 23:17:40,084: INFO: common: created directory at: artifacts/data_validation]
[2024-07-03 23:17:40,084: ERROR: main: 'DataValidation' object has no attribute 'download_file']
Traceback (most recent call last):
  File "c:\Users\heman\OneDrive\Desktop\Text Summariser\main.py", line 9, in <module>
    data_validation .main()
  File "C:\Users\heman\OneDrive\Desktop\Text Summariser\src\textsummariser\pipeline\stage2data_validation.py", line 14, in main
    data_validation.download_file()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataValidation' object has no attribute 'download_file'
[2024-07-03 23:23:06,388: INFO: main: {'Data Validation Stage'}]
[2024-07-03 23:23:06,390: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-03 23:23:06,391: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-03 23:23:06,391: INFO: common: created directory at: artifacts]
[2024-07-03 23:23:06,392: INFO: common: created directory at: artifacts/data_validation]
[2024-07-03 23:23:06,393: ERROR: main: name 'DataValiadtion' is not defined]
Traceback (most recent call last):
  File "c:\Users\heman\OneDrive\Desktop\Text Summariser\main.py", line 9, in <module>
    data_validation .main()
  File "C:\Users\heman\OneDrive\Desktop\Text Summariser\src\textsummariser\pipeline\stage2data_validation.py", line 13, in main
    data_validation = DataValiadtion(config=data_validation_config)
                      ^^^^^^^^^^^^^^
NameError: name 'DataValiadtion' is not defined. Did you mean: 'DataValidation'?
[2024-07-03 23:23:33,947: INFO: main: {'Data Validation Stage'}]
[2024-07-03 23:23:33,949: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-03 23:23:33,950: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-03 23:23:33,950: INFO: common: created directory at: artifacts]
[2024-07-03 23:23:33,950: INFO: common: created directory at: artifacts/data_validation]
[2024-07-03 23:23:33,952: INFO: main: COMPLETED]
[2024-07-05 14:50:06,642: INFO: main: {'Data Validation Stage'}]
[2024-07-05 14:50:06,644: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-05 14:50:06,645: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-05 14:50:06,645: INFO: common: created directory at: artifacts]
[2024-07-05 14:50:06,646: INFO: common: created directory at: artifacts/data_validation]
[2024-07-05 14:50:06,648: INFO: main: COMPLETED]
[2024-07-05 14:54:03,597: INFO: config: PyTorch version 2.3.0 available.]
[2024-07-05 14:54:12,549: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-05 14:54:12,560: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-05 14:54:12,563: INFO: common: created directory at: artifacts]
[2024-07-05 14:55:05,543: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-05 14:55:05,545: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-05 14:55:05,547: INFO: common: created directory at: artifacts]
[2024-07-05 14:55:05,549: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-05 14:56:39,428: INFO: config: PyTorch version 2.3.0 available.]
[2024-07-05 14:56:40,129: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-05 14:56:40,131: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-05 14:56:40,132: INFO: common: created directory at: artifacts]
[2024-07-05 14:59:26,968: INFO: config: PyTorch version 2.3.0 available.]
[2024-07-05 14:59:27,374: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-05 14:59:27,381: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-05 14:59:27,382: INFO: common: created directory at: artifacts]
[2024-07-05 14:59:27,383: INFO: common: created directory at: artifacts/model_evaluation]
[2024-07-05 15:13:11,750: INFO: config: PyTorch version 2.3.0 available.]
[2024-07-05 15:13:12,166: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-05 15:13:12,170: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-05 15:13:12,171: INFO: common: created directory at: artifacts]
[2024-07-05 15:13:12,173: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-05 15:21:34,801: INFO: config: PyTorch version 2.3.1 available.]
[2024-07-05 15:21:35,227: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2024-07-05 15:21:35,229: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-05 15:21:35,230: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-05 15:21:35,230: INFO: common: created directory at: artifacts]
[2024-07-05 15:21:35,230: INFO: common: created directory at: artifacts/data_transformation]
[2024-07-05 15:22:20,753: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2024-07-05 22:46:36,702: INFO: config: PyTorch version 2.3.0 available.]
[2024-07-05 22:46:37,463: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-05 22:46:37,469: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-05 22:46:37,474: INFO: common: created directory at: artifacts]
[2024-07-05 22:52:14,312: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-05 22:52:14,315: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-05 22:52:14,316: INFO: common: created directory at: artifacts]
[2024-07-05 22:52:14,318: INFO: common: created directory at: artifacts/model_trainer]
[2024-07-05 22:53:40,259: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-05 22:53:40,262: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-05 22:53:40,263: INFO: common: created directory at: artifacts]
[2024-07-05 22:53:40,264: INFO: common: created directory at: artifacts/model_trainer]
[2024-07-05 23:02:15,800: INFO: config: PyTorch version 2.3.1 available.]
[2024-07-05 23:02:18,270: INFO: main: *******************]
[2024-07-05 23:02:18,270: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-07-05 23:02:18,272: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-05 23:02:18,274: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-05 23:02:18,275: INFO: common: created directory at: artifacts]
[2024-07-05 23:02:18,275: INFO: common: created directory at: artifacts/model_trainer]
[2024-07-05 23:09:23,101: INFO: config: PyTorch version 2.3.0 available.]
[2024-07-05 23:09:23,632: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-05 23:09:23,638: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-05 23:09:23,640: INFO: common: created directory at: artifacts]
[2024-07-05 23:09:23,642: INFO: common: created directory at: artifacts/model_evaluation]
[2024-07-05 23:14:56,244: INFO: config: PyTorch version 2.3.1 available.]
[2024-07-05 23:14:58,331: INFO: main: *******************]
[2024-07-05 23:14:58,332: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-07-05 23:14:58,334: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-05 23:14:58,336: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-05 23:14:58,336: INFO: common: created directory at: artifacts]
[2024-07-05 23:14:58,336: INFO: common: created directory at: artifacts/model_trainer]
[2024-07-05 23:49:34,290: INFO: server: Started server process [18048]]
[2024-07-05 23:49:34,291: INFO: on: Waiting for application startup.]
[2024-07-05 23:49:34,291: INFO: on: Application startup complete.]
[2024-07-05 23:49:34,292: INFO: server: Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)]
[2024-07-05 23:50:08,315: INFO: server: Shutting down]
[2024-07-05 23:50:08,425: INFO: on: Waiting for application shutdown.]
[2024-07-05 23:50:08,426: INFO: on: Application shutdown complete.]
[2024-07-05 23:50:08,427: INFO: server: Finished server process [18048]]
[2024-07-05 23:50:25,653: INFO: config: PyTorch version 2.3.1 available.]
[2024-07-05 23:50:27,145: INFO: main: *******************]
[2024-07-05 23:50:27,145: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-07-05 23:50:27,147: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-05 23:50:27,149: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-05 23:50:27,149: INFO: common: created directory at: artifacts]
[2024-07-05 23:50:27,150: INFO: common: created directory at: artifacts/model_trainer]
[2024-07-05 23:53:32,026: INFO: config: PyTorch version 2.3.1 available.]
[2024-07-05 23:53:34,313: INFO: main: *******************]
[2024-07-05 23:53:34,313: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2024-07-05 23:53:34,315: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-05 23:53:34,316: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-05 23:53:34,317: INFO: common: created directory at: artifacts]
[2024-07-05 23:53:34,317: INFO: common: created directory at: artifacts/model_trainer]
[2024-07-05 23:55:26,614: INFO: config: PyTorch version 2.3.1 available.]
[2024-07-05 23:55:28,778: INFO: main: *******************]
[2024-07-05 23:55:28,778: INFO: main: >>>>>> stage Model Evaluation stage started <<<<<<]
[2024-07-05 23:55:28,780: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-07-05 23:55:28,781: INFO: common: yaml file: params.yaml loaded successfully]
[2024-07-05 23:55:28,782: INFO: common: created directory at: artifacts]
[2024-07-05 23:55:28,782: INFO: common: created directory at: artifacts/model_evaluation]
[2024-07-05 23:55:28,782: ERROR: main: Incorrect path_or_model_id: 'artifacts/model_trainer/tokenizer'. Please provide either the path to a local folder or the repo_id of a model on the Hub.]
Traceback (most recent call last):
  File "C:\Users\heman\OneDrive\Desktop\Text Summariser\.venv\Lib\site-packages\transformers\utils\hub.py", line 399, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\heman\OneDrive\Desktop\Text Summariser\.venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\Users\heman\OneDrive\Desktop\Text Summariser\.venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'artifacts/model_trainer/tokenizer'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\heman\OneDrive\Desktop\Text Summariser\main.py", line 15, in <module>
    model_evaluation.main()
  File "C:\Users\heman\OneDrive\Desktop\Text Summariser\src\textsummariser\pipeline\stage5model_evaluation.py", line 16, in main
    model_evaluation_config.evaluate()
  File "C:\Users\heman\OneDrive\Desktop\Text Summariser\src\textsummariser\conponents\model_evaluation.py", line 60, in evaluate
    tokenizer = AutoTokenizer.from_pretrained(self.config.tokenizer_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\heman\OneDrive\Desktop\Text Summariser\.venv\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 817, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\heman\OneDrive\Desktop\Text Summariser\.venv\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 649, in get_tokenizer_config
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "C:\Users\heman\OneDrive\Desktop\Text Summariser\.venv\Lib\site-packages\transformers\utils\hub.py", line 463, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'artifacts/model_trainer/tokenizer'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
